### ISSUE TITLE
channel mode +r / s_err / Whois nickname

### ISSUE THREAD

**Issue by WildClaudio** [solbu/Peace-and-Protection#16] opened 2016-05-17 23:15 UTC
i just found that joining a +r(only registered/usernames) allowed to join the channel is wrong  !!! in irc networks that dont use nick registration the Message IS WRONG  saying users that channel is +r +R Registered Nicknames only !!! and wont reffere to a webpage   that the ircd source its sending !!!
[00:07:20] **\* [cannot] join channel- You must have a registered nickname  (mode +R) and the server notice its setup to send the error message like this   **\* [cannot] join channel- You must have a registered username (mode +r) visit http://website.com/username-registration.php

and another on in Whois Replies !!! when you set show Nickname and check "on first line only,but line up the remaining lines !! 

the setup as in Old version should Show nickname in the first line then hide/add the same color as mIRC background to hide nickname in the others lines !!! now will show the nickname in First Line ITS OK but then will BOLD the nickname in the next lines and change the whois color settings from PnP Color Theme into mIRC Color theme !!!

**Comment by solbu** [comment] 2016-05-18 01:47
A change in mIRC, don't remember which version, makes it impossible to script something having both background, and text color the same.color. As in, Khaled who develop mIRC made the change intentionally. It will no longer be allowed to hide text in scripts.

As for the first problem, I'm leaving that to the other developers.

**Comment by craze** [comment] 2016-05-18 12:23
Server notice? So it's an issue with the server then?

**Comment by WildClaudio** [comment] 2016-05-19 01:13
no , its not because without PnP loaded i get the right server notice/error
:\

2016-05-18 13:23 GMT+01:00 Geir André Halle notifications@github.com:

> Server notice? So it's an issue with the server then?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/solbu/Peace-and-Protection/issues/16#issuecomment-220010026

## 

Born To Be Wild

**Comment by craze** [comment] 2016-05-19 09:40
Didn't quite catch what the issue is at first, but have now been able to reproduce the displayed messages related to raw 477 events. Parts of it is defined in the language (translation) files, but there's also the issue with displaying parameters correctly with the theme.

**Comment by ghost** [comment] 2016-07-22 13:08
@WildClaudio You can you override RAW 477 in events.mtp by specifying the following in the theme editor:

`RAW.477 <pre> <text> <comments>`

![image](https://cloud.githubusercontent.com/assets/13683523/17057939/bfda1b40-501d-11e6-9c96-d8f53b9c1784.png)

Can you report back what it does after you add that line of code?

edit:
Joining Freenode #django with [1] and without [2] fix:
![image](https://cloud.githubusercontent.com/assets/13683523/17058224/6aca8200-501f-11e6-906c-347efa7d2f5d.png)

edit2: This seems to be a perm fix for this issue...

**Closed as completed** 2016-07-31 17:17 UTC
