### ISSUE TITLE
Pinging a channel results in multiple windows (@Ping, @Ping[1], @Ping[N] where N is total number of channel users)

### ISSUE THREAD

**Issue by ghost** [solbu/Peace-and-Protection#1] opened 2015-08-09 10:55 UTC

**Comment by ghost** [comment] 2015-08-09 11:10
memo: ctcp.mrc - line 409 - alias ping

![](http://i.imgur.com/BQDci3B.png)

Error:
- Each spread out @Ping [N] Channel window contains only one ping reply instead of all replies for one channel going into one window

**Comment by craze** [comment] 2015-08-09 13:08
Are you sure it's number of channel users and not number of times you've pinged the channel? So far I'm only able to reproduce the screenshot when I ping the channel several times and a @Ping window already exists for that channel, in which case I'd expect it to create a new window without the old info in it.

**Comment by ghost** [comment] 2015-08-09 18:41
https://vimeo.com/135806816

**Comment by ghost** [comment] 2015-08-09 20:37
memo: window.mrc - line 92 - alias _mservwin
alias _mservwin {
  var %cid = $3
  if (!%cid) %cid = $cid
  var %num = 1
  ; String to match
  var %match = /^ $+ $_escape($1) $+ (?:[\d+])? $+ $_escape($2) $+ $!/i
  while (%num <= $window(0)) {
    if ($regex($window(%num),%match)) {
      if ($window(%num).cid == %cid) return $window(%num)
    }
    inc %num
  }
  ; Create new window
  if ($window($1 $+ $2) == $null) return $1 $+ $2
  %num = 2
  while ($window($1 $+ $chr(91) $+ %num $+ $chr(93) $+ $2) != $null) {
    inc %num
  }
  return $1 $+ $chr(91) $+ %num $+ $chr(93) $+ $2
}

memo: aliases.mrc - line 33 - alias _escape
; Escapes all non-alpha characters
_escape var %text = $1- | var %junk = $regsub(%text,/([^a-zA-Z0-9 ])/g,\\1,%text) | return %text

; Replaces all non-alpha characters
_escape2 var %text = $1- | var %junk = $regsub(%text,/([^a-zA-Z0-9])/g,_,%text) | return %text

**Comment by ghost** [comment] 2015-08-09 21:39
In window.mrc - line 105 - alias _mservwin change:

if ($window($1 $+ $2) == $null) return $1 $+ $2

to

if ($window($1 $+ $chr(160) $+ $2) == $null) return $1 $+ $2

**Comment by craze** [comment] 2015-08-09 21:54
In this particular case $chr(160) should already be part of $2. If hardcoded in, will it not break everything else using the _mservwin alias?

**Comment by ghost** [comment] 2015-08-09 22:07
you're right :) but for some reason $chr(160) doesn't get passed.

This works as well:

if ($window($1 $+ $iif($left($2,1) == $chr(160),$chr(160)) $+ $2) == $null) return $1 $+ $2

I find it very strange.

Can you reproduce the error wildcraze or am I the only with this error on mIRC 7.43 and pnp.4.22.3?

**Comment by craze** [comment] 2015-08-09 22:32
It breaks the intended function of _mservwin which is to assign a window name with the lowest number not taken.
In effect the suggested change is just using `var %win = @Ping $+ $chr(160) $+ %target` in the ctcp file (L520) instead of calling the _mservwin alias.
Subsequent pings to a channel, where a new window would make sense, would all end up in the same `@Ping` window as duplicates.

**Comment by ghost** [comment] 2015-08-10 11:55
That's right. I'm merely trying to diagnose why it's not working as intended on my system. I have for the moment changed line 475 and line 520 in **ctcp.mrc** and removed the string `$chr(160) $+` so that line 475 reads: 

`var %win = $_mservwin(@Ping,%ping)`

and line 520 reads:

`var %win = $_mservwin(@Ping,%target)`

Now this seems to work fine. All ping replies go to one @Ping window. I don't have to change anything in alias _mservwin either. Btw craze, from your comments I infer that you don't have this bug on your system. Is that correct?

**Comment by craze** [comment] 2015-08-13 15:29
Appears $regsub behaves a bit different before and after Unicode release of mIRC. Adding (*UTF) to regular expressions responsible for matching window names appears to fix this issue, and is currently being tested.

**Comment by craze** [comment] 2015-08-22 22:57
Fixed in next release, 4.22.6

**Closed as completed by craze** 2015-08-22 22:57 UTC
